spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true

  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
    name: TicketingSystem

  mail:
    host: smtp.gmail.com
    username: arzuahmedova.1707@gmail.com
    password: ylcncsdthkpeedap
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    date-format: dd.MM.yyyy HH:mm
    serialization:
      write-dates-as-timestamps: false     #JsonFormat annotasiyasi bezi yerlerde islemir buna gore bunlari elave etdim


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 300000  # 5 minutes in milliseconds
  refresh-token:
      expiration: 3600000  # 1 hour in milliseconds


info:
  title: Ticketing System API
  version: 1.0
  description: >
   Bu API hem User, hem de admin ucun nezerde tutulub. Common operation-lar hissesinde sisteme hec bir giris ve qeydiyyat teleb
    olunmadan mueyyen melumatlara baxmaq ucun nezerde tutulub. Bu sistemde bir admin var, qalan register olan her bir kes
    User kimi qeydiyyatdan kecir. Admin Operation hissesinde Api-ler Admin ucun nezerde tutulub, User Operation hissesinde
    ise User-e aid yeni login olunduqdan sonra istifade edilen API-lerdir.
  contact:
    name: Arzu Ahmedova
    email: arzuahmedova.1707@gmail.com
server:
  port: 8081



