spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true

  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
    name: TicketingSystem


  mail:
    host: smtp.gmail.com
    username: arzuahmedova.1707@gmail.com
    password: ylcncsdthkpeedap
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    date-format: dd.MM.yyyy HH:mm
    serialization:
      write-dates-as-timestamps: false     #JsonFormat annotasiyasi bezi yerlerde islemir buna gore bunlari elave etdim


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 300000  # 5 minutes in milliseconds
  refresh-token:
      expiration: 3600000  # 1 hour in milliseconds




