spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

  datasource:
    username: user
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
    name: TicketingSystem

  mail:
    host: smtp.gmail.com
    username: arzuahmedova.1707@gmail.com
    password: ylcncsdthkpeedap
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#jwt:
#  secrset: kjhkhdclnladhlnnvqhtr24532yhlij9c-iwijdlnksu9
#  expiration: 3600000



